export const MovieData = [
	
	{
		adult: false,
		backdrop_path: '/keIxh0wPr2Ymj0Btjh4gW7JJ89e.jpg',
		genre_ids: [28, 12, 53, 878],
		id: 497698,
		original_language: 'en',
		original_title: 'Black Widow',
		overview:
			'Natasha Romanoff, also known as Black Widow, confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises. Pursued by a force that will stop at nothing to bring her down, Natasha must deal with her history as a spy and the broken relationships left in her wake long before she became an Avenger.',
		popularity: 7107.473,
		poster_path: '/qAZ0pzat24kLdO3o8ejmbLxyOac.jpg',
		release_date: '2021-07-07',
		title: 'Black Widow',
		video: false,
		vote_average: 8,
		vote_count: 3285,
	},
	{
		adult: false,
		backdrop_path: '/8s4h9friP6Ci3adRGahHARVd76E.jpg',
		genre_ids: [16, 35, 10751, 878],
		id: 379686,
		original_language: 'en',
		original_title: 'Space Jam A New Legacy',
		overview:
			"When LeBron and his young son Dom are trapped in a digital space by a rogue A.I., LeBron must get them home safe by leading Bugs, Lola Bunny and the whole gang of notoriously undisciplined Looney Tunes to victory over the A.I.'s digitized champions on the court. It's Tunes versus Goons in the highest-stakes challenge of his life.",
		popularity: 9054.455,
		poster_path: '/5bFK5d3mVTAvBCXi5NPWH0tYjKl.jpg',
		release_date: '2021-07-08',
		title: 'Space Jam: A New Legacy',
		video: false,
		vote_average: 7.8,
		vote_count: 1185,
	},
	{
		adult: false,
		backdrop_path: '/tehpKMsls621GT9WUQie2Ft6LmP.jpg',
		genre_ids: [12, 53, 28, 27, 37],
		id: 602223,
		original_language: 'en',
		original_title: 'The Forever Purge',
		overview:
			'All the rules are broken as a sect of lawless marauders decides that the annual Purge does not stop at daybreak and instead should never end as they chase a group of immigrants who they want to punish because of their harsh historical past.',
		popularity: 7221.498,
		poster_path: '/uHA5COgDzcxjpYSHHulrKVl6ByL.jpg',
		release_date: '2021-06-30',
		title: 'The Forever Purge',
		video: false,
		vote_average: 7.9,
		vote_count: 535,
	},
	{
		adult: false,
		backdrop_path: '/keIxh0wPr2Ymj0Btjh4gW7JJ89e.jpg',
		genre_ids: [28, 12, 53, 878],
		id: 497698,
		original_language: 'en',
		original_title: 'Black Widow',
		overview:
			'Natasha Romanoff, also known as Black Widow, confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises. Pursued by a force that will stop at nothing to bring her down, Natasha must deal with her history as a spy and the broken relationships left in her wake long before she became an Avenger.',
		popularity: 7107.473,
		poster_path: '/qAZ0pzat24kLdO3o8ejmbLxyOac.jpg',
		release_date: '2021-07-07',
		title: 'Black Widow',
		video: false,
		vote_average: 8,
		vote_count: 3285,
	},
	{
		adult: false,
		backdrop_path: '/gX5UrH1TLVVBwI7WxplW43BD6Z1.jpg',
		genre_ids: [16, 35, 12, 10751],
		id: 459151,
		original_language: 'en',
		original_title: 'The Boss Baby: Family Business',
		overview:
			'The Templeton brothers — Tim and his Boss Baby little bro Ted — have become adults and drifted away from each other. But a new boss baby with a cutting-edge approach and a can-do attitude is about to bring them together again … and inspire a new family business.',
		popularity: 5100.392,
		poster_path: '/5dExO5G2iaaTxYnLIFKLWofDzyI.jpg',
		release_date: '2021-07-01',
		title: 'The Boss Baby: Family Business',
		video: false,
		vote_average: 7.9,
		vote_count: 874,
	},
	{
		adult: false,
		backdrop_path: '/yizL4cEKsVvl17Wc1mGEIrQtM2F.jpg',
		genre_ids: [28, 878],
		id: 588228,
		original_language: 'en',
		original_title: 'The Tomorrow War',
		overview:
			'The world is stunned when a group of time travelers arrive from the year 2051 to deliver an urgent message: Thirty years in the future, mankind is losing a global war against a deadly alien species. The only hope for survival is for soldiers and civilians from the present to be transported to the future and join the fight. Among those recruited is high school teacher and family man Dan Forester. Determined to save the world for his young daughter, Dan teams up with a brilliant scientist and his estranged father in a desperate quest to rewrite the fate of the planet.',
		popularity: 4066.42,
		poster_path: '/34nDCQZwaEvsy4CFO5hkGRFDCVU.jpg',
		release_date: '2021-06-30',
		title: 'The Tomorrow War',
		video: false,
		vote_average: 8.3,
		vote_count: 2847,
	},
	{
		adult: false,
		backdrop_path: '/620hnMVLu6RSZW6a5rwO8gqpt0t.jpg',
		genre_ids: [16, 35, 10751, 14],
		id: 508943,
		original_language: 'en',
		original_title: 'Luca',
		overview:
			'Luca and his best friend Alberto experience an unforgettable summer on the Italian Riviera. But all the fun is threatened by a deeply-held secret: they are sea monsters from another world just below the water’s surface.',
		popularity: 3383.138,
		poster_path: '/jTswp6KyDYKtvC52GbHagrZbGvD.jpg',
		release_date: '2021-06-17',
		title: 'Luca',
		video: false,
		vote_average: 8.1,
		vote_count: 3202,
	},
	{
		adult: false,
		backdrop_path: '/3RMbkXS4ocMmoJyAD3ZsWbm32Kx.jpg',
		genre_ids: [28, 12, 18, 878, 53],
		id: 615658,
		original_language: 'en',
		original_title: 'Awake',
		overview:
			'After a sudden global event wipes out all electronics and takes away humankind’s ability to sleep, chaos quickly begins to consume the world. Only Jill, an ex-soldier with a troubled past, may hold the key to a cure in the form of her own daughter. The question is, can Jill safely deliver her daughter and save the world before she herself loses her mind.',
		popularity: 3030.751,
		poster_path: '/1OTa0PfX2axMY8f9tFRSzESUgkC.jpg',
		release_date: '2021-06-09',
		title: 'Awake',
		video: false,
		vote_average: 6.1,
		vote_count: 545,
	},
	{
		adult: false,
		backdrop_path: '/wjQXZTlFM3PVEUmKf1sUajjygqT.jpg',
		genre_ids: [878, 28, 53],
		id: 581726,
		original_language: 'en',
		original_title: 'Infinite',
		overview:
			'Evan McCauley has skills he never learned and memories of places he has never visited. Self-medicated and on the brink of a mental breakdown, a secret group that call themselves “Infinites” come to his rescue, revealing that his memories are real.',
		popularity: 2914.38,
		poster_path: '/niw2AKHz6XmwiRMLWaoyAOAti0G.jpg',
		release_date: '2021-06-10',
		title: 'Infinite',
		video: false,
		vote_average: 7.3,
		vote_count: 538,
	},
	{
		adult: false,
		backdrop_path: '/xXHZeb1yhJvnSHPzZDqee0zfMb6.jpg',
		genre_ids: [28, 12, 80, 53],
		id: 385128,
		original_language: 'en',
		original_title: 'F9',
		overview:
			"Dominic Toretto and his crew battle the most skilled assassin and high-performance driver they've ever encountered: his forsaken brother.",
		popularity: 2381.183,
		poster_path: '/bOFaAXmWWXC3Rbv4u4uM9ZSzRXP.jpg',
		release_date: '2021-05-19',
		title: 'F9',
		video: false,
		vote_average: 7.5,
		vote_count: 721,
	},
	{
		adult: false,
		backdrop_path: '/70AV2Xx5FQYj20labp0EGdbjI6E.jpg',
		genre_ids: [80, 28, 53],
		id: 637649,
		original_language: 'en',
		original_title: 'Wrath of Man',
		overview:
			"A cold and mysterious new security guard for a Los Angeles cash truck company surprises his co-workers when he unleashes precision skills during a heist. The crew is left wondering who he is and where he came from. Soon, the marksman's ultimate motive becomes clear as he takes dramatic and irrevocable steps to settle a score.",
		popularity: 2369.428,
		poster_path: '/M7SUK85sKjaStg4TKhlAVyGlz3.jpg',
		release_date: '2021-04-22',
		title: 'Wrath of Man',
		video: false,
		vote_average: 7.8,
		vote_count: 1537,
	},
	{
		adult: false,
		backdrop_path: '/6MKr3KgOLmzOP6MSuZERO41Lpkt.jpg',
		genre_ids: [35, 80],
		id: 337404,
		original_language: 'en',
		original_title: 'Cruella',
		overview:
			'In 1970s London amidst the punk rock revolution, a young grifter named Estella is determined to make a name for herself with her designs. She befriends a pair of young thieves who appreciate her appetite for mischief, and together they are able to build a life for themselves on the London streets. One day, Estella’s flair for fashion catches the eye of the Baroness von Hellman, a fashion legend who is devastatingly chic and terrifyingly haute. But their relationship sets in motion a course of events and revelations that will cause Estella to embrace her wicked side and become the raucous, fashionable and revenge-bent Cruella.',
		popularity: 2111.396,
		poster_path: '/rTh4K5uw9HypmpGslcKd4QfHl93.jpg',
		release_date: '2021-05-26',
		title: 'Cruella',
		video: false,
		vote_average: 8.4,
		vote_count: 4322,
	},
	{
		adult: false,
		backdrop_path: '/5HjzYTihkH7EvOWSE7KcsF6pBMM.jpg',
		genre_ids: [10751, 35, 12, 16, 14],
		id: 522478,
		original_language: 'en',
		original_title: 'Peter Rabbit 2: The Runaway',
		overview:
			'Bea, Thomas, and the rabbits have created a makeshift family, but despite his best efforts, Peter can’t seem to shake his mischievous reputation. Adventuring out of the garden, Peter finds himself in a world where his mischief is appreciated, but when his family risks everything to come looking for him, Peter must figure out what kind of bunny he wants to be.',
		popularity: 1987.614,
		poster_path: '/cycDz68DtTjJrDJ1fV8EBq2Xdpb.jpg',
		release_date: '2021-03-25',
		title: 'Peter Rabbit 2: The Runaway',
		video: false,
		vote_average: 7.4,
		vote_count: 197,
	},
	{
		adult: false,
		backdrop_path: '/x9p2syPxeK2OYCpz35fsg0EFjlG.jpg',
		genre_ids: [16, 35],
		id: 834404,
		original_language: 'en',
		original_title: 'Teen Titans Go! See Space Jam',
		overview:
			"The Teen Titans are visited by the Nerdlucks, the Space Jam villains who tried to capture Michael Jordan and the Looney Tunes. Astonished to discover his fellow Titans have never seen Space Jam, Cyborg organizes an exclusive watch party. Of course, if the Titans are watching a movie, don't expect silence to be golden. Raven and Starfire provide the commentary, Cyborg presents the fun facts, Beast Boy points out the butt shots, and Robin, but Robin doesn't trust their new alien friends. Are the Nerdlucks here to attend an innocent watch party, or do they have more sinister motives up their sleeves?",
		popularity: 1975.963,
		poster_path: '/j0pJ7e2ZGdzo9yEV7c6TLBue8Co.jpg',
		release_date: '2021-06-20',
		title: 'Teen Titans Go! See Space Jam',
		video: false,
		vote_average: 7.3,
		vote_count: 65,
	},
	{
		adult: false,
		backdrop_path: '/zsH3iW60T1t2HBTtrSKzzxJ406J.jpg',
		genre_ids: [16, 35, 10751],
		id: 846214,
		original_language: 'en',
		original_title: 'The Simpsons: The Good, the Bart, and the Loki',
		overview:
			'Loki is banished from Asgard once again and must face his toughest opponents yet: the Simpsons and Springfield’s mightiest heroes. The God of Mischief teams up with Bart Simpson in the ultimate crossover event paying tribute to the Marvel Cinematic Universe of superheroes and villains.',
		popularity: 1966.973,
		poster_path: '/rtMdtzywcAGOrF6t8fbxJBqpdcq.jpg',
		release_date: '2021-07-07',
		title: 'The Simpsons: The Good, the Bart, and the Loki',
		video: false,
		vote_average: 8,
		vote_count: 292,
	},
	{
		adult: false,
		backdrop_path: '/AsqUSUqXrK8JfH8WEQnCXVbIAv6.jpg',
		genre_ids: [878, 53, 27],
		id: 520763,
		original_language: 'en',
		original_title: 'A Quiet Place Part II',
		overview:
			'Following the events at home, the Abbott family now face the terrors of the outside world. Forced to venture into the unknown, they realize that the creatures that hunt by sound are not the only threats that lurk beyond the sand path.',
		popularity: 1789.293,
		poster_path: '/4q2hz2m8hubgvijz8Ez0T2Os2Yv.jpg',
		release_date: '2021-05-21',
		title: 'A Quiet Place Part II',
		video: false,
		vote_average: 7.7,
		vote_count: 2153,
	},
	{
		adult: false,
		backdrop_path: '/ok7RdHhVngnwkvKj09tvtOvypG.jpg',
		genre_ids: [80, 18, 53, 9648],
		id: 649409,
		original_language: 'en',
		original_title: 'No Sudden Move',
		overview:
			"A group of criminals are brought together under mysterious circumstances and have to work together to uncover what's really going on when their simple job goes completely sideways.",
		popularity: 1575.559,
		poster_path: '/34BmdJkdvRweC3xJJFlOFQ2IbYc.jpg',
		release_date: '2021-06-24',
		title: 'No Sudden Move',
		video: false,
		vote_average: 6.7,
		vote_count: 125,
	},
	{
		adult: false,
		backdrop_path: '/c0izdYdnTe4uMRifHgvTA85wPz0.jpg',
		genre_ids: [28, 80, 27],
		id: 503736,
		original_language: 'en',
		original_title: 'Army of the Dead',
		overview:
			'Following a zombie outbreak in Las Vegas, a group of mercenaries take the ultimate gamble: venturing into the quarantine zone to pull off the greatest heist ever attempted.',
		popularity: 1431.844,
		poster_path: '/z8CExJekGrEThbpMXAmCFvvgoJR.jpg',
		release_date: '2021-05-14',
		title: 'Army of the Dead',
		video: false,
		vote_average: 6.4,
		vote_count: 2003,
	},
	{
		adult: false,
		backdrop_path: '/qi6Edc1OPcyENecGtz8TF0DUr9e.jpg',
		genre_ids: [27, 9648, 53],
		id: 423108,
		original_language: 'en',
		original_title: 'The Conjuring: The Devil Made Me Do It',
		overview:
			"Paranormal investigators Ed and Lorraine Warren encounter what would become one of the most sensational cases from their files. The fight for the soul of a young boy takes them beyond anything they'd ever seen before, to mark the first time in U.S. history that a murder suspect would claim demonic possession as a defense.",
		popularity: 1392.701,
		poster_path: '/xbSuFiJbbBWCkyCCKIMfuDCA4yV.jpg',
		release_date: '2021-05-25',
		title: 'The Conjuring: The Devil Made Me Do It',
		video: false,
		vote_average: 7.9,
		vote_count: 3200,
	},
	{
		adult: false,
		backdrop_path: '/pVNXmfZvQKFdUKVYNJxZAiy69DC.jpg',
		genre_ids: [28, 12],
		id: 529106,
		original_language: 'ru',
		original_title: 'Майор Гром: Чумной Доктор',
		overview:
			'Igor Grom is a skilled policeman from St. Petersburg, known for his daring nature and uncompromising attitude towards the criminals of all kinds. Incredible strength, analytical mind and integrity – these qualities make Major Grom the perfect policeman. Working tirelessly, he always pushes through, and meets the challenges standing in the way.',
		popularity: 1276.292,
		poster_path: '/wnesEmcq7xdw1Rm1Bn6XEFTkenR.jpg',
		release_date: '2021-04-01',
		title: 'Major Grom: Plague Doctor',
		video: false,
		vote_average: 7,
		vote_count: 206,
	},
	{
		adult: false,
		backdrop_path: '/9yBVqNruk6Ykrwc32qrK2TIE5xw.jpg',
		genre_ids: [28, 14, 12],
		id: 460465,
		original_language: 'en',
		original_title: 'Mortal Kombat',
		overview:
			"Washed-up MMA fighter Cole Young, unaware of his heritage, and hunted by Emperor Shang Tsung's best warrior, Sub-Zero, seeks out and trains with Earth's greatest champions as he prepares to stand against the enemies of Outworld in a high stakes battle for the universe.",
		popularity: 1248.029,
		poster_path: '/nkayOAUBUu4mMvyNf9iHSUiPjF1.jpg',
		release_date: '2021-04-07',
		title: 'Mortal Kombat',
		video: false,
		vote_average: 7.5,
		vote_count: 3373,
	},
	{
		adult: false,
		backdrop_path: '/inJjDhCjfhh3RtrJWBmmDqeuSYC.jpg',
		genre_ids: [28, 12, 14],
		id: 399566,
		original_language: 'en',
		original_title: 'Godzilla vs. Kong',
		overview:
			'In a time when monsters walk the Earth, humanity’s fight for its future sets Godzilla and Kong on a collision course that will see the two most powerful forces of nature on the planet collide in a spectacular battle for the ages.',
		popularity: 1140.526,
		poster_path: '/pgqgaUx1cJb5oZQQ5v0tNARCeBp.jpg',
		release_date: '2021-03-24',
		title: 'Godzilla vs. Kong',
		video: false,
		vote_average: 8,
		vote_count: 6491,
	},
	{
		adult: false,
		backdrop_path: '/A0xW7GgeFQoQmPOn7HcHkBQ5nlb.jpg',
		genre_ids: [53, 28],
		id: 817451,
		original_language: 'en',
		original_title: 'Endangered Species',
		overview:
			'Jack Halsey takes his wife, their adult kids, and a friend for a dream vacation in Kenya. But as they venture off alone into a wilderness park, their safari van is flipped over by an angry rhino, leaving them injured and desperate. Then, as two of them go in search of rescue, a bloody, vicious encounter with a leopard and a clan of hyenas incites a desperate fight for survival.',
		popularity: 1113.31,
		poster_path: '/ccsSqbpEqr2KK9eMvoeF8ERFCd5.jpg',
		release_date: '2021-05-27',
		title: 'Endangered Species',
		video: false,
		vote_average: 6.3,
		vote_count: 68,
	},
	{
		adult: false,
		backdrop_path: '/fPGeS6jgdLovQAKunNHX8l0avCy.jpg',
		genre_ids: [28, 53, 10752],
		id: 567189,
		original_language: 'en',
		original_title: "Tom Clancy's Without Remorse",
		overview:
			'An elite Navy SEAL uncovers an international conspiracy while seeking justice for the murder of his pregnant wife.',
		popularity: 1048.881,
		poster_path: '/rEm96ib0sPiZBADNKBHKBv5bve9.jpg',
		release_date: '2021-04-29',
		title: "Tom Clancy's Without Remorse",
		video: false,
		vote_average: 7.2,
		vote_count: 1398,
	},
	{
		adult: false,
		backdrop_path: '/6viJBbovWxJYavdjPy7UPTLvaOS.jpg',
		genre_ids: [9648, 27],
		id: 591275,
		original_language: 'en',
		original_title: 'Fear Street: 1666',
		overview:
			"In 1666, a colonial town is gripped by a hysterical witch-hunt that has deadly consequences for centuries to come, and it's up to teenagers in 1994 to finally put an end to their town's curse, before it's too late.",
		popularity: 1043.712,
		poster_path: '/rmEPtz3Ufzol2VWUAZYzOFaBio3.jpg',
		release_date: '2021-07-16',
		title: 'Fear Street: 1666',
		video: false,
		vote_average: 7.6,
		vote_count: 454,
	},
	{
		adult: false,
		backdrop_path: '/jWMWZ2ttg8B8YtVzG04UfhlcL67.jpg',
		genre_ids: [28, 53],
		id: 809314,
		original_language: 'en',
		original_title: 'Trigger Point',
		overview:
			"Nicolas Shaw is a retired U.S. special operative who becomes part of an elite 'invisible' team that quietly takes out the worst villains around the world.",
		popularity: 1039.802,
		poster_path: '/qlXenN6jjgbsIyEJxBjkfkEU0q8.jpg',
		release_date: '2021-04-23',
		title: 'Trigger Point',
		video: false,
		vote_average: 6.3,
		vote_count: 68,
	},
	{
		adult: false,
		backdrop_path: null,
		genre_ids: [28, 80],
		id: 385687,
		original_language: 'en',
		original_title: 'Fast & Furious 10',
		overview: 'The tenth installment in the Fast Saga.',
		popularity: 1039.122,
		poster_path: '/2DyEk84XnbJEdPlGF43crxfdtHH.jpg',
		title: 'Fast & Furious 10',
		video: false,
		vote_average: 0,
		vote_count: 0,
	},
	{
		adult: false,
		backdrop_path: '/iJ2HVOZT9Kjayrhy21pbGIJs9ey.jpg',
		genre_ids: [28, 12, 14],
		id: 525660,
		original_language: 'cn',
		original_title: '真·三国无双',
		overview:
			'Warlords, warriors and statesmen wage a battle for supremacy in this fantasy tale based on the hit video games and the "Romance of the Three Kingdoms."',
		popularity: 1023.154,
		poster_path: '/7BCTdek5LFHglcgl7shsm7igJAH.jpg',
		release_date: '2021-04-29',
		title: 'Dynasty Warriors',
		video: false,
		vote_average: 6.5,
		vote_count: 42,
	},
	{
		adult: false,
		backdrop_path: '/5Zv5KmgZzdIvXz2KC3n0MyecSNL.jpg',
		genre_ids: [28, 53, 80],
		id: 634528,
		original_language: 'en',
		original_title: 'The Marksman',
		overview:
			'Jim Hanson’s quiet life is suddenly disturbed by two people crossing the US/Mexico border – a woman and her young son – desperate to flee a Mexican cartel. After a shootout leaves the mother dead, Jim becomes the boy’s reluctant defender. He embraces his role as Miguel’s protector and will stop at nothing to get him to safety, as they go on the run from the relentless assassins.\r Stars...Liam Neeson',
		popularity: 1006.419,
		poster_path: '/6vcDalR50RWa309vBH1NLmG2rjQ.jpg',
		release_date: '2021-01-15',
		title: 'The Marksman',
		video: false,
		vote_average: 7.3,
		vote_count: 691,
	},
	{
		adult: false,
		backdrop_path: '/5C8bfwglg91uZhc2fbfpSjNGamV.jpg',
		genre_ids: [27, 9648],
		id: 591273,
		original_language: 'en',
		original_title: 'Fear Street: 1994',
		overview:
			'In 1994, a group of teenagers discovers that the terrifying events which have haunted their town for generations ​are all connected — and that they may be the next targets.',
		popularity: 984.138,
		poster_path: '/9J9Wy39ZjrVmfk7yMkulpcI5sy0.jpg',
		release_date: '2021-06-28',
		title: 'Fear Street: 1994',
		video: false,
		vote_average: 6.8,
		vote_count: 768,
	},
	{
		adult: false,
		backdrop_path: '/xPpXYnCWfjkt3zzE0dpCNME1pXF.jpg',
		genre_ids: [16, 28, 12, 14],
		id: 635302,
		original_language: 'ja',
		original_title: '劇場版「鬼滅の刃」無限列車編',
		overview:
			"Tanjirō Kamado, joined with Inosuke Hashibira, a boy raised by boars who wears a boar's head, and Zenitsu Agatsuma, a scared boy who reveals his true power when he sleeps, boards the Infinity Train on a new mission with the Fire Hashira, Kyōjurō Rengoku, to defeat a demon who has been tormenting the people and killing the demon slayers who oppose it!",
		popularity: 928.58,
		poster_path: '/h8Rb9gBr48ODIwYUttZNYeMWeUU.jpg',
		release_date: '2020-10-16',
		title: 'Demon Slayer -Kimetsu no Yaiba- The Movie: Mugen Train',
		video: false,
		vote_average: 8.4,
		vote_count: 1417,
	},
	{
		adult: false,
		backdrop_path: '/rlNnwObbMu5G2FaOUlacnUIdIIA.jpg',
		genre_ids: [16, 35, 10751, 12],
		id: 726684,
		original_language: 'fr',
		original_title: 'Miraculous World : Shanghai, la légende de Ladydragon',
		overview:
			'On school break, Marinette heads to Shanghai to meet Adrien. But after arriving, Marinette loses all her stuff, including the Miraculous that allows her to turn into Ladybug!',
		popularity: 924.085,
		poster_path: '/qQ0VKsGRQ2ofAmswGNzZnvC1xPE.jpg',
		release_date: '2021-04-04',
		title: 'Miraculous World: Shanghai – The Legend of Ladydragon',
		video: false,
		vote_average: 7.9,
		vote_count: 510,
	},
	{
		adult: false,
		backdrop_path: '/yC4DRg5aGgNpkHpUDpLtBqzownS.jpg',
		genre_ids: [878, 28],
		id: 586047,
		original_language: 'ko',
		original_title: '서복',
		overview:
			'A former intelligence agent gets involved with the first human clone, Seo Bok, who others seek, causing trouble.',
		popularity: 916.502,
		poster_path: '/nxxuWC32Y6TULj4VnVwMPUFLIpK.jpg',
		release_date: '2021-04-12',
		title: 'Seobok',
		video: false,
		vote_average: 7.7,
		vote_count: 68,
	},
	{
		adult: false,
		backdrop_path: '/vqEjXzWdzPbV2DZ7bk29weDFiDl.jpg',
		genre_ids: [16, 12, 10751, 37],
		id: 637693,
		original_language: 'en',
		original_title: 'Spirit Untamed',
		overview:
			"Lucky Prescott's life is changed forever when she moves from her home in the city to a small frontier town and befriends a wild mustang named Spirit.",
		popularity: 869.495,
		poster_path: '/5cbGVDmRMYVzkq5cItZ7cYlDdDR.jpg',
		release_date: '2021-05-20',
		title: 'Spirit Untamed',
		video: false,
		vote_average: 7.7,
		vote_count: 174,
	},
	{
		adult: false,
		backdrop_path: '/pcDc2WJAYGJTTvRSEIpRZwM3Ola.jpg',
		genre_ids: [28, 12, 14, 878],
		id: 791373,
		original_language: 'en',
		original_title: "Zack Snyder's Justice League",
		overview:
			"Determined to ensure Superman's ultimate sacrifice was not in vain, Bruce Wayne aligns forces with Diana Prince with plans to recruit a team of metahumans to protect the world from an approaching threat of catastrophic proportions.",
		popularity: 859.125,
		poster_path: '/tnAuB8q5vv7Ax9UAEje5Xi4BXik.jpg',
		release_date: '2021-03-18',
		title: "Zack Snyder's Justice League",
		video: false,
		vote_average: 8.4,
		vote_count: 6120,
	},
	{
		adult: false,
		backdrop_path: '/h9DIlghaiTxbQbt1FIwKNbQvEL.jpg',
		genre_ids: [28, 12, 53],
		id: 581387,
		original_language: 'ko',
		original_title: '백두산',
		overview:
			'A group of unlikely heroes from across the Korean peninsula try to save the day after a volcano erupts on the mythical and majestic Baekdu Mountain.',
		popularity: 834.477,
		poster_path: '/8WzoEWgwsaPuUuu7XhInFV3YCxy.jpg',
		release_date: '2019-12-19',
		title: 'Ashfall',
		video: false,
		vote_average: 6.4,
		vote_count: 295,
	},
	{
		adult: false,
		backdrop_path: '/lQxiU6AxQqdX1npMH450SocUZ0g.jpg',
		genre_ids: [35, 18],
		id: 633954,
		original_language: 'fr',
		original_title: 'Le guide de la famille parfaite',
		overview:
			'A couple in Québec deals with the pitfalls, pressure and high expectations of raising kids in a society obsessed with success and social media image.',
		popularity: 812.671,
		poster_path: '/cBhkSwZpb3QpUwFuFdWAXTqWAtS.jpg',
		release_date: '2021-07-14',
		title: 'The Guide to the Perfect Family',
		video: false,
		vote_average: 6.8,
		vote_count: 46,
	},
	{
		adult: false,
		backdrop_path: '/sXw75q37IsFWgIIrjMZwfCXO1BF.jpg',
		genre_ids: [27, 9648],
		id: 591274,
		original_language: 'en',
		original_title: 'Fear Street: 1978',
		overview:
			"In 1978, two rival groups at Camp Nightwing must band together to solve a terrifying mystery when horrors from their towns' history come alive.",
		popularity: 811.665,
		poster_path: '/5dNTxhoGDTHHGqUTdxcr4H1dqlU.jpg',
		release_date: '2021-07-09',
		title: 'Fear Street: 1978',
		video: false,
		vote_average: 7.5,
		vote_count: 603,
	},
	{
		adult: false,
		backdrop_path: '/6zbKgwgaaCyyBXE4Sun4oWQfQmi.jpg',
		genre_ids: [28, 80, 18],
		id: 615457,
		original_language: 'en',
		original_title: 'Nobody',
		overview:
			'Hutch Mansell, a suburban dad, overlooked husband, nothing neighbor — a "nobody." When two thieves break into his home one night, Hutch\'s unknown long-simmering rage is ignited and propels him on a brutal path that will uncover dark secrets he fought to leave behind.',
		popularity: 804.262,
		poster_path: '/oBgWY00bEFeZ9N25wWVyuQddbAo.jpg',
		release_date: '2021-03-26',
		title: 'Nobody',
		video: false,
		vote_average: 8.4,
		vote_count: 2773,
	},
	{
		adult: false,
		backdrop_path: '/c7dFSqZQYqNNJVpacpIGZe3gkLW.jpg',
		genre_ids: [16, 35, 14],
		id: 813258,
		original_language: 'en',
		original_title: 'Monster Pets: A Hotel Transylvania Short',
		overview:
			'Drac tries out some new monster pets to help occupy Tinkles for playtime.',
		popularity: 793.872,
		poster_path: '/dkokENeY5Ka30BFgWAqk14mbnGs.jpg',
		release_date: '2021-04-02',
		title: 'Monster Pets: A Hotel Transylvania Short',
		video: false,
		vote_average: 7.6,
		vote_count: 199,
	},
	{
		adult: false,
		backdrop_path: '/jw6ASGRT2gi8EjCImpGtbiJ9NQ9.jpg',
		genre_ids: [27],
		id: 632357,
		original_language: 'en',
		original_title: 'The Unholy',
		overview:
			'Alice, a young hearing-impaired girl who, after a supposed visitation from the Virgin Mary, is inexplicably able to hear, speak and heal the sick. As word spreads and people from near and far flock to witness her miracles, a disgraced journalist hoping to revive his career visits the small New England town to investigate. When terrifying events begin to happen all around, he starts to question if these phenomena are the works of the Virgin Mary or something much more sinister.',
		popularity: 785.932,
		poster_path: '/bShgiEQoPnWdw4LBrYT5u18JF34.jpg',
		release_date: '2021-03-31',
		title: 'The Unholy',
		video: false,
		vote_average: 6.9,
		vote_count: 1212,
	},
];
